name: CMake Build (Windows x86 (686))

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".gitignore"
      - "docs/**"
      - "README"
      - "CREDITS.TXT"
      - "COPYING_GLIB"
      - "COPYING.LGPL2"
      - "AUTHORS.TXT"
      - "CHANGELOG"
      - "COPYING"
  pull_request:

env:
  VCPKG_COMMIT: 2ad004460f5db4d3b66f62f5799ff66c265c4b5d
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
#  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW32
          update: true

    - name: Install dependencies
      run: pacman -Sq --noconfirm git make mingw-w64-i686-{cmake,SDL2,libslirp,libarchive,libepoxy,toolchain}

    - name: Create build environment
      working-directory: ${{ runner.workspace }}
      run: mkdir build

    - name: Configure
      working-directory: ${{ runner.workspace }}/build
      run: >
        cmake ../../melonDS-x86-Updated
        -G "MinGW Makefiles"
        -DCMAKE_BUILD_TYPE=Release
        -DMELONDS_EMBED_BUILD_INFO=ON
        -DUSE_VCPKG=OFF
        -DBUILD_STATIC=OFF
        -DBUILD_QT_SDL=OFF
        -DENABLE_OGLRENDERER=OFF

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config Release

    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-i686
        path: ${{ runner.workspace }}\build\melonDS.exe
